AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

  golang-sam-bootstrap
  SAM Template for golang-sam-bootstrap

#####  Globals for Lambda functions #####
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        Region: "eu-west-1"

#####  Input Parameters #####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default

#####  Environment Variables #####
Mappings:
  StagesMap:
    sandbox:
      VariableName: Value
    staging:
      VariableName: Value
    production:
      VariableName: Value

#####  Template Conditions #####
Conditions:
  CreateSandboxResources: !Equals [!Ref Stage, sandbox]

Resources:
  #####  Lambda Functions #####
  S3FileProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/package/
      Handler: s3-file-processor
      Runtime: go1.x
      MemorySize: 128
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref SuccessFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FailureFunction
      Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*

  SuccessFunction:
    Type: AWS::Serverless::Function
    Description: This is a function to be executed upon the success of s3 file processor
    Properties:
      CodeUri: ./build/package/
      Handler: success-handler
      Runtime: go1.x

  FailureFunction:
    Type: AWS::Serverless::Function
    Description: This is a function to be executed upon the failure of s3 file processor
    Properties:
      CodeUri: ./build/package/
      Handler: failure-handler
      Runtime: go1.x

#####  Resources #####
  ResourceSaveInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    DependsOn:
      - S3FileProcessorFunction
      - SuccessFunction
      - FailureFunction
    Properties:
      FunctionName: !Ref S3FileProcessorFunction
      Qualifier: "$LATEST"
      MaximumEventAgeInSeconds: 600
      MaximumRetryAttempts: 1
      DestinationConfig:
        OnSuccess:
          Destination: !GetAtt SuccessFunction.Arn
        OnFailure:
          Destination: !GetAtt FailureFunction.Arn

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: lambda-destination-bucket-1911